name: Create Release
on:
  push:
    branches: [master]

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 12
            registry-url: https://npm.pkg.github.com/
            scope: "@lkmx"
        - run: git config --global user.email "$GITHUB_ACTOR@lkmx.io" && git config --global user.name "$GITHUB_ACTOR"
        - run: npm config set tag-version-prefix ''
        - run: npm version minor
        - run: git push --tags && git push
        - run: npm publish
          env:
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
